# Generated by Django 4.0.6 on 2022-07-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_id_symbol_symbol_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='symbol_id',
            new_name='id',
        ),
    ]
