# Generated by Django 4.0.6 on 2022-07-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_symbol_id_symbol_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='id',
            new_name='symbol_id',
        ),
    ]
