# Generated by Django 4.0.6 on 2022-07-22 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_id_symbol_symbol_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='symbol_id',
        ),
        migrations.AddField(
            model_name='symbol',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
