# Generated by Django 4.0.6 on 2022-07-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_symbol_symbol_id_symbol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='id',
            field=models.UUIDField(default='urn:uuid:9cb55d62-e3ff-41be-9123-e8e3a53c675e', editable=False, primary_key=True, serialize=False),
        ),
    ]
