# Generated by Django 4.0.6 on 2022-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_symbol_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='id',
        ),
        migrations.AddField(
            model_name='symbol',
            name='symbol_id',
            field=models.UUIDField(default='urn:uuid:275c1759-1761-482d-9fd8-a68233eda174', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
