# Generated by Django 4.0.6 on 2022-07-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_symbol_id_symbol_symbol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.UUIDField(default=103706372087746367684920175764493114095, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
