# Generated by Django 4.0.6 on 2022-07-24 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_signal_symbol_current_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.UUIDField(default=5447780342603736160952646710479982754, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('price', models.FloatField()),
                ('time', models.DateTimeField()),
                ('current_profit', models.FloatField()),
                ('max_profit', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('failed', 'Failed')], max_length=6, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.symbol')),
            ],
        ),
    ]
