# Generated by Django 4.0.6 on 2022-07-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_symbol_symbol_id_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='symbol',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.UUIDField(default=139595587106958300545424928252678596291, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
