# Generated by Django 4.0.6 on 2022-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_signal_high_signal_low_symbol_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.UUIDField(default=337605015060312309758271062383446435745, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
