# Generated by Django 4.0.6 on 2022-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_signal_status_alter_symbol_symbol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='current_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='signal',
            name='max_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('failed', 'Failed'), ('successful', 'Successful')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.UUIDField(default=137910473724303131595344328730594304654, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
