# Generated by Django 4.0.6 on 2022-07-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_signal_current_profit_alter_signal_max_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.UUIDField(default=235119507558394887843185575272953914857, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
