# Generated by Django 4.0.6 on 2022-07-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_symbol_symbol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.UUIDField(default='urn:uuid:82df45e8-f03c-4f91-b63d-a3c8f95d6a7d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
