# Generated by Django 4.0.6 on 2022-07-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_symbol_symbol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.CharField(default='urn:uuid:141177fe-b06b-4a8b-b16f-429453c56def', editable=False, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
