# Generated by Django 4.0.6 on 2022-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_symbol_symbol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.CharField(default='urn:uuid:f0e36b97-91f9-4831-acd7-4d7d62862fc1', editable=False, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
