# Generated by Django 4.0.6 on 2022-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_symbol_symbol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.CharField(default='9fc9eba0b65f4cf89b08c6211e9662a1', editable=False, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
