# Generated by Django 4.0.6 on 2022-07-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_symbol_symbol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol_id',
            field=models.CharField(default='4f91eeac88784df08b188f331c9ac416', editable=False, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
