# Generated by Django 4.0.6 on 2022-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_symbol_symbol_alter_symbol_symbol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], default='green', max_length=10),
        ),
    ]
