# Generated by Django 4.0.6 on 2022-11-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_signal_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('symbol', models.CharField(max_length=500)),
                ('exchange', models.CharField(max_length=500)),
            ],
        ),
    ]
