# Generated by Django 4.0.6 on 2023-05-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['time']},
        ),
    ]
